# Generated by Django 5.0.7 on 2024-07-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descripation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
